---
- name: Is httpd package installed?
  shell: rpm -qa | grep httpd-
  register: result_rpm
  ignore_errors: yes

- name: Is index.html is exist?
  shell: test -e /var/www/html/index.html
  register: result_file
  ignore_errors: yes

- name: Is httpd processes are started?
  shell: ps -ef | grep http[d]
  register: result_proc
  ignore_errors: yes

- name: Is port 80 is opened?
  wait_for:
    host: localhost
    port: 80
    timeout: 3
  register: result_port
  ignore_errors: yes

- name: Does the server return 200 OK?
  uri:
    url: http://localhost/
    follow_redirects: none
    status_code: 200
  register: result_url
  ignore_errors: yes

- name: check test results
  assert:
    that: "{{ result.failed == false }}"
  loop:
    - "{{ result_rpm }}"
    - "{{ result_file }}"
    - "{{ result_proc }}"
    - "{{ result_port }}"
    - "{{ result_url }}"
  loop_control:
    loop_var: result
